### ISSUE TITLE
“多图上传”中浏览“在线管理”，及“附件”中浏览“在线附件”时出现错误

### ISSUE THREAD

**Issue by cttoy** [durow/UEditorNetCore#1]
先感谢durow，正好用上!

--------------------错误如下--------------------------------------

An unhandled exception occurred while processing the request. 
InvalidOperationException: Incorrect Content-Type:
Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
UEditorNetCore.Handlers.ListFileManager.Process()
UEditorNetCore.UEditorActionCollection.ListFileAction(HttpContext context)
UEditorNetCore.UEditorService.DoAction(HttpContext context)
MyXXXProject.Controllers.UEditorController.Do() in UEditorController.cs
....

经查是 /Handlers/ListFileHandler.cs中的Request.Form引起的，修改为Request.Query后问题解决。

**Comment by durow** [comment]
多谢多谢，刚刚修复了下，再次感谢 :)
